require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'sailraceapp2' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => FlipperConfiguration.disabled,
    :fabric_enabled => false, # explicitly disable fabric if causing issues
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'sailraceapp2Tests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)', '$(SRCROOT)/../../node_modules/react-native/React']
      end
    end
  end
end
